# Generated by Django 4.1.1 on 2023-12-20 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedagogie', '0002_categorie_service_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accompagnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('methode', models.TextField()),
                ('conseil_acc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AdminScolaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.TextField()),
                ('conseil', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='service',
            old_name='type',
            new_name='type_service',
        ),
    ]
