# Generated by Django 4.1.1 on 2023-12-21 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedagogie', '0004_adminscolaire_type_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='accompagnement',
            name='type_acc',
            field=models.CharField(choices=[('Coaching', 'Coaching'), ('Soutient Scolaire', 'Soutient Scolaire')], default='Coaching', max_length=123),
        ),
    ]
