# Generated by Django 4.1.1 on 2023-12-20 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_service', models.CharField(max_length=32)),
                ('desc_service', models.TextField()),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.categorie')),
            ],
        ),
        migrations.CreateModel(
            name='Livres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=64)),
                ('auteur', models.CharField(max_length=32)),
                ('description', models.TextField()),
                ('date_ajout', models.DateTimeField(auto_now=True)),
                ('type_livre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.categorie')),
            ],
        ),
        migrations.CreateModel(
            name='EcolePartenaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='media/logo_ecole')),
                ('nom_ecole', models.CharField(max_length=64)),
                ('adresse', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=128)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.service')),
            ],
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre_document', models.CharField(max_length=32)),
                ('contenu', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/img_doc')),
                ('video', models.FileField(upload_to='media/video_doc')),
                ('type_doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.categorie')),
            ],
        ),
    ]
