# Generated by Django 4.1.1 on 2023-12-20 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedagogie', '0001_initial'),
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecolepartenaire',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedagogie.service'),
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
