# Generated by Django 4.1.1 on 2023-12-20 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0003_alter_documents_type_doc_alter_livres_type_livre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(max_length=128)),
            ],
        ),
        migrations.AlterField(
            model_name='documents',
            name='type_doc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.categorie'),
        ),
        migrations.AlterField(
            model_name='livres',
            name='type_livre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.categorie'),
        ),
    ]
