# Generated by Django 4.1.1 on 2024-01-22 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0005_alter_documents_type_doc_alter_livres_type_livre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='media/video_doc'),
        ),
    ]
