# Generated by Django 4.1.1 on 2024-01-23 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0006_alter_documents_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='livres',
            name='img_livre',
            field=models.ImageField(blank=True, null=True, upload_to='media/img_livre'),
        ),
    ]
